# Generated by Django 4.2.1 on 2023-07-08 21:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_packages_category_testimonial_packages_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(upload_to='gallery')),
                ('gallery_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_image', models.ImageField(upload_to='instagram_image')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Packages/')),
                ('des', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='PackagesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Packages_Category/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subscribe_email', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Packages_Add',
        ),
        migrations.DeleteModel(
            name='Packages_Category',
        ),
        migrations.AddField(
            model_name='packages',
            name='packages_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.packagescategory'),
        ),
        migrations.AddField(
            model_name='packagedetails',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.packages'),
        ),
    ]
