# Generated by Django 4.2.1 on 2023-07-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gallery_instagram_packagedetails_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='packagescategory',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
